/* al cargar resulltados de la base de datos, se llena automaticamente cada contenedor de elementos */
/* COSAS POR HACER: 
1. CREAR ELEMENTOS JSON O ALMENOS RECIBIRLOS Y GUARDAR EN ARREGLOS
2. MANDAR A LLAMAR LAS FUNCIONES PARA CARGA DE ELEMENTOS DINAMICOS
3. FUNCION DE BUSQUEDA ESPECIFICA PARA MOSTRAR ELEMENTO ESPECIFICO
*/
function Buscardor(categoria, nombre){
	/* INICIO DE BUSQUEDA PARA OBTENER RESULTADOS A TRAVES DE NOMBRE */
}


function AccederTitulo(id, nombre, tipo){
	// VER ELEMENTO ESPECIFICO
}